/**
 * Sync published magazine markdown into D1 SQL.
 *
 * Markdown under src/content/blog remains an authoring input. D1 is the
 * serving source of truth. This script never imports the parked English archive.
 *
 * Usage:
 *   npx tsx scripts/sync-articles-to-d1.ts --sql-out /tmp/seed-articles.sql
 *   wrangler d1 execute linguafly_db --local --file=/tmp/seed-articles.sql
 *   wrangler d1 execute linguafly_db --remote --file=/tmp/seed-articles.sql
 */
import fs from "node:fs";
import path from "node:path";
import { getBlogArticles } from "../src/lib/blog";
import { blogPostToArticleInput } from "../src/lib/content/map-article";
import {
  articleUpsertBindings,
  ftsKeywords,
  type ArticleInput,
} from "../src/lib/db/client";

const UPSERT_SQL = `INSERT INTO articles (
  slug, title, description, content, category, level,
  excerpt, author, read_time, faqs, featured, image, alt,
  related_routes, canonical, created_at, updated_at, is_published
) VALUES`;

function argValue(flag: string): string | undefined {
  const index = process.argv.indexOf(flag);
  if (index === -1) return undefined;
  return process.argv[index + 1];
}

function sqlLiteral(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

function articleSql(article: ArticleInput): string {
  const values = articleUpsertBindings(article).map(sqlLiteral).join(", ");
  const tags = article.tags ?? [];
  const tagDeletes = `DELETE FROM article_tags WHERE article_id IN (SELECT id FROM articles WHERE slug = ${sqlLiteral(article.slug)});`;
  const tagInserts = tags
    .map(
      (tag) =>
        `INSERT INTO article_tags (article_id, tag) SELECT id, ${sqlLiteral(tag)} FROM articles WHERE slug = ${sqlLiteral(article.slug)};`
    )
    .join("\n");
  const ftsDelete = `DELETE FROM articles_fts WHERE slug = ${sqlLiteral(article.slug)};`;
  const ftsInsert = `INSERT INTO articles_fts (slug, title, excerpt, description, keywords, category, content) VALUES (${[
    article.slug,
    article.title,
    article.excerpt ?? article.description ?? "",
    article.description ?? "",
    ftsKeywords(article.tags),
    article.category,
    article.content,
  ]
    .map(sqlLiteral)
    .join(", ")});`;

  return [
    `${UPSERT_SQL} (${values})`,
    `ON CONFLICT(slug) DO UPDATE SET
  title = excluded.title,
  description = excluded.description,
  content = excluded.content,
  category = excluded.category,
  level = excluded.level,
  excerpt = excluded.excerpt,
  author = excluded.author,
  read_time = excluded.read_time,
  faqs = excluded.faqs,
  featured = excluded.featured,
  image = excluded.image,
  alt = excluded.alt,
  related_routes = excluded.related_routes,
  canonical = excluded.canonical,
  created_at = COALESCE(excluded.created_at, articles.created_at),
  updated_at = excluded.updated_at,
  is_published = excluded.is_published;`,
    tagDeletes,
    tagInserts,
    ftsDelete,
    ftsInsert,
  ]
    .filter(Boolean)
    .join("\n");
}

function main() {
  const sqlOut = argValue("--sql-out");
  const articles = getBlogArticles();
  if (articles.length === 0) {
    throw new Error(
      "[sync-articles-to-d1] 0 artículos públicos en markdown. Abortando para no vaciar D1."
    );
  }

  const inputs = articles.map(blogPostToArticleInput);
  const sql = [
    "-- Generated by scripts/sync-articles-to-d1.ts. Public magazine articles only.",
    `PRAGMA foreign_keys = ON;`,
    ...inputs.map(articleSql),
    "",
  ].join("\n\n");

  if (!sqlOut) {
    console.log(sql);
    console.error(
      `[sync-articles-to-d1] ${inputs.length} artículos. Pasa --sql-out <file> para escribir el SQL.`
    );
    return;
  }

  const outPath = path.resolve(sqlOut);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, sql);
  console.log(
    `[sync-articles-to-d1] ${inputs.length} artículos → ${outPath} (${(Buffer.byteLength(sql) / 1024).toFixed(1)} KiB)`
  );
}

main();
