/**
 * Sync public magazine + English-learning markdown into D1 SQL.
 *
 * Markdown under src/content/blog remains an authoring input. D1 is the
 * serving source of truth. Unique key is (category, slug) so course units
 * that share a filename across levels do not overwrite each other.
 *
 * Usage:
 *   npx tsx scripts/sync-articles-to-d1.ts --sql-out /tmp/seed-articles.sql
 *   npx tsx scripts/sync-articles-to-d1.ts --sql-out-dir /tmp/d1-seed
 *   wrangler d1 execute linguafly_db --local --file=/tmp/d1-seed/001.sql
 */
import fs from "node:fs";
import path from "node:path";
import { getArticlesForD1Sync } from "../src/lib/blog";
import { blogPostToArticleInput } from "../src/lib/content/map-article";
import {
  articleUpsertBindings,
  ftsKeywords,
  type ArticleInput,
} from "../src/lib/db/client";

/** Keep each file small enough for wrangler d1 execute (long article bodies). */
const ARTICLES_PER_CHUNK = 8;

const UPSERT_SQL = `INSERT INTO articles (
  slug, title, description, content, category, level,
  excerpt, author, read_time, faqs, featured, image, alt,
  related_routes, canonical, created_at, updated_at, is_published
) VALUES`;

function argValue(flag: string): string | undefined {
  const index = process.argv.indexOf(flag);
  if (index === -1) return undefined;
  return process.argv[index + 1];
}

function sqlLiteral(value: unknown): string {
  if (value === null || value === undefined) return "NULL";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "NULL";
  return `'${String(value).replace(/'/g, "''")}'`;
}

function articleSql(article: ArticleInput): string {
  const values = articleUpsertBindings(article).map(sqlLiteral).join(", ");
  const tags = article.tags ?? [];
  const slug = sqlLiteral(article.slug);
  const category = sqlLiteral(article.category);
  const tagDeletes = `DELETE FROM article_tags WHERE article_id IN (SELECT id FROM articles WHERE slug = ${slug} AND category = ${category});`;
  const tagInserts = tags
    .map(
      (tag) =>
        `INSERT INTO article_tags (article_id, tag) SELECT id, ${sqlLiteral(tag)} FROM articles WHERE slug = ${slug} AND category = ${category};`
    )
    .join("\n");
  const ftsDelete = `DELETE FROM articles_fts WHERE slug = ${slug} AND category = ${category};`;
  const ftsInsert = `INSERT INTO articles_fts (slug, title, excerpt, description, keywords, category, content) VALUES (${[
    article.slug,
    article.title,
    article.excerpt ?? article.description ?? "",
    article.description ?? "",
    ftsKeywords(article.tags),
    article.category,
    article.content,
  ]
    .map(sqlLiteral)
    .join(", ")});`;

  return [
    `${UPSERT_SQL} (${values})`,
    `ON CONFLICT(category, slug) DO UPDATE SET
  title = excluded.title,
  description = excluded.description,
  content = excluded.content,
  category = excluded.category,
  level = excluded.level,
  excerpt = excluded.excerpt,
  author = excluded.author,
  read_time = excluded.read_time,
  faqs = excluded.faqs,
  featured = excluded.featured,
  image = excluded.image,
  alt = excluded.alt,
  related_routes = excluded.related_routes,
  canonical = excluded.canonical,
  created_at = COALESCE(excluded.created_at, articles.created_at),
  updated_at = excluded.updated_at,
  is_published = excluded.is_published;`,
    tagDeletes,
    tagInserts,
    ftsDelete,
    ftsInsert,
  ]
    .filter(Boolean)
    .join("\n");
}

function chunk<T>(items: T[], size: number): T[][] {
  const out: T[][] = [];
  for (let i = 0; i < items.length; i += size) {
    out.push(items.slice(i, i + size));
  }
  return out;
}

function sqlDocument(inputs: ArticleInput[], note: string): string {
  return [
    "-- Generated by scripts/sync-articles-to-d1.ts.",
    `-- ${note}`,
    `PRAGMA foreign_keys = ON;`,
    ...inputs.map(articleSql),
    "",
  ].join("\n\n");
}

function main() {
  const sqlOut = argValue("--sql-out");
  const sqlOutDir = argValue("--sql-out-dir");
  const articles = getArticlesForD1Sync();
  if (articles.length === 0) {
    throw new Error(
      "[sync-articles-to-d1] 0 artículos públicos en markdown. Abortando para no vaciar D1."
    );
  }

  const inputs = articles.map((article) => ({
    ...blogPostToArticleInput(article),
    isPublished: true,
  }));

  if (sqlOutDir) {
    const dir = path.resolve(sqlOutDir);
    fs.mkdirSync(dir, { recursive: true });
    const chunks = chunk(inputs, ARTICLES_PER_CHUNK);
    chunks.forEach((part, index) => {
      const name = `${String(index + 1).padStart(3, "0")}.sql`;
      const filePath = path.join(dir, name);
      const sql = sqlDocument(
        part,
        `chunk ${index + 1}/${chunks.length} (${part.length} artículos)`
      );
      fs.writeFileSync(filePath, sql);
    });
    const bytes = chunks.reduce((sum, part, index) => {
      const name = `${String(index + 1).padStart(3, "0")}.sql`;
      return sum + fs.statSync(path.join(dir, name)).size;
    }, 0);
    console.log(
      `[sync-articles-to-d1] ${inputs.length} artículos → ${chunks.length} archivos en ${dir} (${(bytes / 1024 / 1024).toFixed(2)} MiB)`
    );
    return;
  }

  const sql = sqlDocument(inputs, `${inputs.length} artículos (revista + archivo de inglés)`);

  if (!sqlOut) {
    console.log(sql);
    console.error(
      `[sync-articles-to-d1] ${inputs.length} artículos. Pasa --sql-out <file> o --sql-out-dir <dir>.`
    );
    return;
  }

  const outPath = path.resolve(sqlOut);
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, sql);
  console.log(
    `[sync-articles-to-d1] ${inputs.length} artículos → ${outPath} (${(Buffer.byteLength(sql) / 1024).toFixed(1)} KiB)`
  );
}

main();
