/**
 * Cloudflare Environment Types
 * Auto-generated by: npm run cf-typegen
 */

type D1Database = any;
type KVNamespace = any;
type R2Bucket = any;
type AnalyticsEngineDataset = any;

export interface CloudflareEnv {
  DB: D1Database;
  CACHE: KVNamespace;
  SEARCH_INDEX: KVNamespace;
  ARTICLES_BUCKET: R2Bucket;
  ANALYTICS: AnalyticsEngineDataset;
  ARTICLES_API_KEY?: string;
  ENVIRONMENT?: string;
}

declare global {
  interface Window {
    CF_ENV: CloudflareEnv;
  }
}
